#!/bin/bash


# include bash_private if it exists
if [ -f ~/.secrets/bash_private ]; then
   . ~/.secrets/bash_private
fi

# include rdev_helpers if it exists
if [ -f ~/dotfiles/rdev_bash_helpers ]; then
   . ~/dotfiles/rdev_bash_helpers
fi

export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

##### methods
##get info on port 9000 or some other specified port
port() {
  echo "Running lsof -n -iTCP: on ports 9000 thru 9005 and 9999, 4443, 4200"
  for i in {9000..9005} 
    do
      echo "Port $i: $(lsof -n -iTCP:$i)"
    # alternative command - might be more redhat friendly: lsof -n -iTCP:$i
    done
    echo "Port 9999: $(lsof -n -iTCP:9999)"
    echo "Port 4443: $(lsof -n -iTCP:4443)"
    echo "Port 4200: $(lsof -n -iTCP:4200)"
}

##toggle the host file from local, server1, server2 
toggleHost() {
  echo "Get server IP with: getServerIp"
  read -r line < /etc/hosts
  if [[ $line = *"local"* ]]; then
    echo "Toggling the host file from local to server1"
    sudo cp /etc/hosts_server1 /etc/hosts
  elif [[ $line = *"server1"* ]]; then
    echo "Toggling the host file from server1 to server2"
    sudo cp /etc/hosts_server2 /etc/hosts
  else
    echo "Toggling the host file from server2 to local"
    sudo cp /etc/hosts_local /etc/hosts
  fi
}

##get server ip address via ssh cmd
getServerIp() {
  if [ -z $SERVER_BOX ]; then echo "Expected var $SERVER_BOX to be set for this utility. Please add this to your bash config."
  else
    echo "server ip: $(ssh $SERVER_BOX "hostname -I" | awk '{print $1}' FS=" ")"
  fi
  if [ -z $SERVER_BOX_@ ]; then echo "Can add  var $SERVER_BOX_2 to be set for this utility."
  else
    echo "server_2 ip: $(ssh $SERVER_BOX_2 "hostname -I" | awk '{print $1}' FS=" ")"
  fi
}

#alias rgi="rg --type-add 'web:*.{html,css,scss,hbs,tl,js}' --type-add 'scss:*.scss' --type-add 'test:*{test,Test,TEST}*'" 
rg() {
    if [ -t 1 ]; then
        command rg -p "$@" | less -RFX
    else
        command rg "$@"
    fi
}

##### aliases
alias vim='vi'
alias evim='vim ~/dotfiles/vim/vimrc'
alias egit='vim ~/dotfiles/gitconfig'
alias etmux='vim ~/.tmux.conf'
alias rzsh='. ~/.zshrc'
alias ezsh='vim ~/.zshrc'
alias rbash='. ~/.bash_profile'
alias ebash='vim ~/.bash_profile'
alias ebashz='vim ~/dotfiles/bash_zsh_common'
alias erip='vim ~/.ripgreprc'
alias ewatch='vim ~/.watchman-processor.config.js'
alias code='code .'
alias ..='cd ..'
alias l='ls -l'
alias ll='ls -la'
alias lll='ls -lha'
alias notes='cd ~/Dropbox/notes/work'
alias nox='vim ~/Dropbox/notes/work'

# wip - not working right now. Revisit later
#alias runHeadTests="ember exam --path dist --file-path $(git diff HEAD^ HEAD --name-only -- "*test*" | awk 'ORS=","' | sed 's/,$/\n/')"
alias otherTest="git diff HEAD^ HEAD --name-only -- '*test*' | tr '\n' ',' | sed 's/.$//' | (read p1; ember exam --path dist --file-path "$p1")"
alias tmp2="git diff HEAD^ HEAD --name-only -- '*test*' | tr '\n' ',' | sed 's/.$//' | (read p1; echo ember exam --path dist --file=path $p1)"
alias tmp3="git diff HEAD^ HEAD --name-only -- '*test*' | tr '\n' ',' | sed 's/.$//' | xargs echo"
