#!/bin/bash

export NODE_OPTIONS="--max-old-space-size=1638994"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
export PATH=$PATH:/opt/homebrew/bin
export PATH=$PATH:/export/content/linkedin/bin

# the z dir completion helper
. ~/dotfiles/scripts/z.sh

# rdev instance-specific settings
if [[ "$(uname)" == "Linux" ]]; then
  # source executables
  export PATH=$PATH:~/dotfiles/bin

fi

# include rdev_helpers if it exists
if [[ -f ~/dotfiles/rdev_bash_helpers ]]; then
   . ~/dotfiles/rdev_bash_helpers
fi

export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

##### methods
##get info on port 9000 or some other specified ports
port() {
  echo "Running lsof -n -iTCP: on ports 9000 thru 9005 and 9999, 4443, 4200"
  for i in {9000..9005} 
    do
      echo "Port $i: $(lsof -n -iTCP:$i)"
    # alternative command - might be more redhat friendly: lsof -n -iTCP:$i
    done
    echo "Port 9999: $(lsof -n -iTCP:9999)"
    echo "Port 4443: $(lsof -n -iTCP:4443)"
    echo "Port 4200: $(lsof -n -iTCP:4200)"
}

##toggle the host file from local, server1, server2 
toggleHost() {
  read -r line < /etc/hosts
  if [[ $line = *"local"* ]]; then
    echo "Toggling the host file from local to server1"
    sudo cp /etc/hosts_server1 /etc/hosts
  elif [[ $line = *"server1"* ]]; then
    echo "Toggling the host file from server1 to server2"
    sudo cp /etc/hosts_server2 /etc/hosts
  else
    echo "Toggling the host file from server2 to local"
    sudo cp /etc/hosts_local /etc/hosts
  fi
}

rg() {
    if [[ -t 1 ]]; then
        command rg -p "$@" | less -RFX
    else
        command rg "$@"
    fi
}

##### aliases
alias evim='vim ~/dotfiles/vim/vimrc'
alias egit='vim ~/dotfiles/gitconfig'
alias rzsh='. ~/.zshrc'
alias ezsh='vim ~/.zshrc'
alias rbash='. ~/.bashrc'
alias ebash='vim ~/.bashrc'
alias ebashz='vim ~/dotfiles/bash_zsh_common'
alias erip='vim ~/.ripgreprc'
alias code='code .'
alias ..='cd ..'
alias l='ls -l'
alias ll='ls -la'
alias lll='ls -lha'
