#!/bin/bash

#######################################
# Run ember exam against a set of files
# Flags:
# -c: (default) run test files from git unstaged changes, i.e., test files you seen in 'git status'
# -d: run test files in from git head
# -h: help
# files[,files]: run supplied test files
#######################################
emberTests() {
  gitHead_flag=''
  gitChanges_flag=''
  help_flag=''
  listOfTestFiles=''
  finalTestFiles=''
  filter=''
  server_flag=''

  # handle a set of command flags
  unset opt OPTARG OPTIND
  while getopts 'cdf:hs' flag; do
    case "${flag}" in
      c ) gitChanges_flag="true" ;;
      d ) gitHead_flag="true" ;;
      f ) filter="${OPTARG}" ;;
      h ) help_flag="true" ;;
      s ) server_flag="--server" ;;
    esac
  done

  # determine which (if any) test files we're going to run
  if [[ -z "$1" ]]; then
    # default to '-c' param if no arguments passed in
    emberTests -c
    return 1
  elif [[ "$gitChanges_flag" == "true" ]]; then
    echo "Testing files in git status:"
    listOfTestFiles=$(git status --porcelain | sed s/^...// | grep test)
    echo "$listOfTestFiles"
    finalTestFiles=$(echo "$listOfTestFiles" | tr '\n' ',' | sed 's/.$//')
  elif [[ "$gitHead_flag" == "true" ]]; then
    echo "Testing files in git HEAD:"
    listOfTestFiles=$(git diff HEAD^ HEAD --name-only -- '*test*')
    echo "$listOfTestFiles"
    finalTestFiles=$(echo "$listOfTestFiles" | tr '\n' ',' | sed 's/.$//' | xargs echo)
  elif [[ "$help_flag" == "true" ]]; then
    echo "emberTests is a helper for plugging a set of test files into 'ember exam --path dist --file-path'"
    echo ""
    echo "Usage:"
    echo "-c (default) - run test files from git unstaged changes (see 'git status')"
    echo "-d - run test files from files in git head"
    echo "\"filePath[,otherFilePath]\" - file paths of tests to run"
    echo "-f \"filter string\": filter to apply to limit tests in supplied file set"
  elif [[ $1 == -* ]]; then
    # looks like a param was passed that was not caught here
    echo "Unrecognized parameter. Trying running the command with the help (-h) flag"
  else
    echo "Assuming you've passed in a file/files"
    echo "Passing the following to ember exam:"
    finalTestFiles=$1
    echo $finalTestFiles
  fi

  # exit early since there are no files to test and we'll wait forever if this gets passed to ember exam
  if [[ -z "$finalTestFiles" ]]; then
    return 1
  fi

  # run the tests
  if [[ -z "$filter" ]]; then
    ember exam --path dist --file-path ${finalTestFiles} ${server_flag}
  else
    echo ""
    echo "Filtering for: ${filter}"
    echo ""
    ember exam --path dist --file-path ${finalTestFiles} --filter ${filter} ${server_flag}
  fi
}
