#!/bin/bash

# Detect the shell
CURRENT_SHELL=$(ps -p $$ -ocomm=)

# Environment Variables (shared)
export NODE_OPTIONS="--max-old-space-size=1638994"
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Environment Variables (shared)
export NODE_OPTIONS="--max-old-space-size=1638994"
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Setup PATH
PATH="/opt/homebrew/bin"
PATH="$PATH:$HOME/.volta/bin"
PATH="$PATH:$HOME/.cargo/bin"
PATH="$PATH:$(go env GOPATH)/bin"
PATH="$PATH:$HOME/dev/zoink_dev/bin"
PATH="$PATH:/export/content/linkedin/bin"
PATH="$PATH:/usr/local/linkedin/bin"
PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH


# NVM (shared)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

if [[ "$CURRENT_SHELL" == "bash" ]]; then
  # Switch to ZSH if available and correct path
  # if [[ -x "$(command -v zsh)" ]]; then
  #   echo "Switching to ZSH"
  #   export SHELL="$(command -v zsh)"
  #   [[ $- == *i* ]] && exec "$SHELL"
  # fi
  echo "Using BASH, did not attempt to switch to ZSH"
  # Custom Bash prompt
  if [[ "$(uname)" == "Darwin" ]]; then
    export PS1='\[\e[1;32m\]\h\[\e[m\]\[\e[1;30m\]\w\[\e[m\]\[\e[1;35m\]$\[\e[m\]\[\e[1;32m\]\[\e[m\] '
  else
    export PS1='\[\e[1;33m\]\h@\w$\[\e[m\] '
  fi

  export LSCOLORS=GxFxCxDxBxegedabagaced
  export CLICOLOR=1
fi

# Aliases
alias evim='vim ~/dotfiles/vim/vimrc'
alias egit='vim ~/dotfiles/gitconfig'
alias rzsh='. ~/.zshrc'
alias ezsh='vim ~/.zshrc'
alias rbash='. ~/.bashrc'
alias ebash='vim ~/.bashrc'
alias erip='vim ~/.ripgreprc'
alias code='code .'
alias ..='cd ..'
alias l='ls -l'
alias ll='ls -la'
alias lll='ls -lha'

# Functions
port() {
  echo "Checking ports 9000-9005, 9999, 4443, 4200"
  for i in {9000..9005} 9999 4443 4200; do
    echo "Port $i: $(lsof -n -iTCP:$i)"
  done
}

toggleHost() {
  case "$(head -n1 /etc/hosts)" in
    *local*)  sudo cp /etc/hosts_server1 /etc/hosts ;;
    *server1*) sudo cp /etc/hosts_server2 /etc/hosts ;;
    *) sudo cp /etc/hosts_local /etc/hosts ;;
  esac
}
